import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google"; // Import Roboto font
import "./globals.css";
import { Providers } from "./reduxrtk/providers";
import NavbarWrapper from "./component/Header/NavbarWrapper"; // Import the new wrapper
import FooterWrapper from "./component/Footer/FooterWrapper";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto", // Define CSS variable for Roboto
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], // Include different weights
});

export const metadata = {
  title: "PunyaSetu",
  description: "Generated by Daksh Infosoft",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="https://www.punyasetu.com/assets/images/logo.png" sizes="any" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} font-roboto antialiased`}
      >
        <Providers>
        <ToastContainer position="top-right" autoClose={5000} />
          <NavbarWrapper /> {/* Use NavbarWrapper instead of Navbar */}
          {children}
          <FooterWrapper/>
        </Providers>
      </body>
    </html>
  );
}
