"use client";

import { useState, useEffect } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./reduxrtk/providers";
import NavbarWrapper from "./component/Header/NavbarWrapper";
import FooterWrapper from "./component/Footer/FooterWrapper";
import { ToastContainer } from "react-toastify";
import { LanguageProvider } from "../context/LanguageContext.js";
import "./lib/i18n";
import I18nProvider from "./providers";
import { FaArrowUp } from "react-icons/fa"; // Import back-to-top icon
import LoadingScreen from "./component/LoadingScreen";
import { setLoadingFunction } from "./utils/loadingState";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({ children }) {
  const [showButton, setShowButton] = useState(false);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoadingFunction(setLoading);
  }, []);

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 300) {
        setShowButton(true);
      } else {
        setShowButton(false);
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };
   const metadata = {
    title: "PunyaSetu",
    description: "Generated by Daksh Infosoft",
  };
  return (
    <html lang="en">
      <link
        rel="icon"
        href="https://www.punyasetu.com/assets/images/logo.png"
        sizes="any"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} font-roboto antialiased bg-white text-black`}
      >
        <Providers>
          <LanguageProvider>
            <ToastContainer position="top-right" autoClose={5000} />
            <NavbarWrapper data-translate />

            <I18nProvider>
            {loading && <LoadingScreen />}
              {children}
              </I18nProvider>
            <FooterWrapper />

            {/* 🔹 Back to Top Button */}
            {showButton && (
              <button
                onClick={scrollToTop}
                className="fixed bottom-10 right-5 lg:right-10 bg-orange-600 text-white lg:p-5 p-3 rounded-full shadow-md hover:bg-orange-700 transition-all"
              >
                <FaArrowUp className="text-lg" />
              </button>
            )}
          </LanguageProvider>
        </Providers>
      </body>
    </html>
  );
}
