// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";

import { LanguageProvider } from "../context/LanguageContext";
import I18nProvider from "./providers";
import ClientLayout from "./ClientLayout";

// Fonts
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});
<meta name="google-site-verification" content="z24DoP8dSzClbNxAWfBPKHQ_sv1bQE1MFEkUOSKvPyc" />
// Metadata
export const metadata = {
  title: "LatestAutoTech",
  description: "Generated by Daksh Infosoft",
  icons: {
    icon: "/favicon.ico", // Place your favicon in /public/
  },
  
};
<meta name="google-site-verification" content="z24DoP8dSzClbNxAWfBPKHQ_sv1bQE1MFEkUOSKvPyc" />

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} font-roboto antialiased bg-white text-black`}>
   
          <LanguageProvider>
            <I18nProvider>
              <ClientLayout>{children}</ClientLayout>
            </I18nProvider>
          </LanguageProvider>
        
      </body>
    </html>
  );
}
