"use client";

import React, { useRef, useEffect } from "react";
import { Splide, SplideSlide } from "@splidejs/react-splide";
import "@splidejs/splide/css";
import { usePathname } from "next/navigation";
import { IoIosArrowBack, IoIosArrowForward } from "react-icons/io";
import { useTranslation } from "react-i18next";

const Homeeight = ({ pujaData, detail }) => {
  const { t } = useTranslation();
  const splideRef = useRef(null); // Reference for Splide instance
  const pathname = usePathname(); 
  const testimonials = pujaData?.data?.testimonials || detail?.testimonials || [];

  const isSpecialPage = pathname.includes("/poojadetail/");

  useEffect(() => {
    if (splideRef.current) {
      setTimeout(() => {
        const pagination = document.querySelector(".splide__pagination");
        if (pagination) {
          pagination.classList.add("flex", "justify-center", "items-center", "gap-2");
          pagination.style.display = "flex";
        }
      }, 100);
    }
  }, []);


  return (
    <div className={`py-10 ${isSpecialPage ? "bg-[#FFDCC0] " : "bg-white"} p-6 transition-all  duration-300`}>
  
      <div className="mb-8 text-center">
        <h2 className="text-gray-800 text-[42px] font-bold">
        {t("WhatOurClientsSayAboutUs")}
        </h2>
      </div>

      <div className="relative w-full mx-auto ">
        {/* Slider */}
        <Splide
          ref={splideRef}
          options={{
            type: "loop",
            perPage: 3,
            breakpoints: {
              1024: { perPage: 2 },
              768: { perPage: 1 },
              480: { perPage: 1 },
            },
            focus: "center",
            padding: { left: "1rem", right: "1rem" },
            gap: "1rem",
            autoplay: true,
            interval: 3000,
            pauseOnHover: true,
            arrows: false, // Disable default arrows (we use custom below)
            pagination: true, // Keep pagination (dots)
          }}
          className="w-full"
        >
          {testimonials && testimonials.length > 0 ? (
  testimonials.map((testimonial, index) => (
    <SplideSlide key={testimonial.id || index}>
      <div className="p-6 mx-auto relative max-w-md mb-10 bg-white rounded-lg shadow-lg">
        <div className="flex items-center gap-4">
          {/* Client image */}
          <img
            src={testimonial?.image || "https://readymadeui.com/team-2.webp"}
            className="w-14 h-14 rounded-full border-2 shadow shadow-2xl"
            alt={testimonial?.name || "Client"}
          />
          <div>
            {/* Client name */}
            <h4 className="text-gray-800 text-lg font-semibold">
              {testimonial?.name || "Client Name"}
            </h4>
          </div>
        </div>

        {/* Testimonial short description */}
        <p className="font-semibold text-black mt-4">
          {testimonial?.testimonials_description
            ? testimonial.testimonials_description.split("\r\n")[0].slice(0, 50) +
              (testimonial.testimonials_description.split("\r\n")[0].length > 50 ? "..." : "")
            : "It was a very good experience"}
        </p>

        {/* Full testimonial description */}
        <div className="mt-4">
          <p className="text-sm text-black">
            {testimonial?.testimonials_description?.split("\r\n")[1] ||
              "The service was amazing. I never had to wait that long for my food."}
          </p>
        </div>
      </div>
    </SplideSlide>
  ))
) : (
  <div className="text-center text-gray-500 text-lg font-semibold py-10">No data available</div>
)}

        </Splide>

        {/* Custom Navigation Below */}
        <div className="flex justify-center items-center absolute -bottom-2 inset-x-0  gap-8">
          {/* Left Arrow */}
          <button
            className="text-2xl text-gray-700 p-2 rounded-full"
            onClick={() => splideRef.current.splide.go("-1")}
          >
            <IoIosArrowBack   className="text-3xl"/>
          </button>

          {/* Pagination (Dots - Auto-generated by Splide) */}
          <div className="splide__pagination "></div>

          {/* Right Arrow */}
          <button
            className=" text-gray-700 p-2 rounded-full"
            onClick={() => splideRef.current.splide.go("+1")}
          >
          <IoIosArrowForward className="text-3xl" />

          </button>
        </div>
      </div>
    </div>
  );
};

export default Homeeight;
